import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Headline from "@/components/Navbar/Headline";
import Navbar from "@/components/Navbar/Navbar";
import Footer from "@/components/Footer/Footer";
import HomeHeader from "@/components/Navbar/HomeHeader";
import FeedsHeader from "@/components/Navbar/FeedsHeader";
import MenuHeader from "@/components/Navbar/MenuHeader";
import NextAuthProvider from "@/provider/NextAuthProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "JonoBad",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`} 
    >
      <body className="min-h-full flex flex-col">
        <NextAuthProvider>
        <Headline />

        <header className="sticky top-0 z-50 hidden md:block ">
          <Navbar />
        </header>

        <header className="block lg:hidden">
          <HomeHeader />
        </header>

        <header>
               <FeedsHeader />
        </header>
        
        <header>
          <MenuHeader />
        </header>

        <main>

        {children}
        </main>


        <Footer />

</NextAuthProvider>
      </body>
    </html>
  );
}
